### PR TITLE
Rewrite using Babel

### PR DESCRIPTION
**Pull request by TimothyGu**
The primary goal of this change is to allow using next-generation JavaScript features, and also JavaScript extensions not currently implemented in Acorn.

I rewrote the entire module with Babel, instead of just porting the original module to Babylon. Compare to the original source-based approach, this is obviously more robust; but it also means that module is slower (about 13x slower than before in my tests). The most time is spent traversing through the AST.

I also wrote this module to be stand-alone, so that the user doesn't have to install Babel herself, and the API is identical as before. However, I believe it would be easier if we could convert the module to a Babel plugin, so that in addition to enjoying the simplicity of having Babel handling things for us the performance would also be improved if other Babel plugins are used, since Babel would merge all visitors and traverse the AST only once.

Lastly there is also the option of directly porting the module to Babylon without using any of Babel's utilities, but I feel it would produce a lot of duplicated work, and not worth the effort.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
My suspicion is that working with babylon directly might give us back some of that 13x slowdown.  Porting it to a babel-plugin (in a separate repo) would make a fair bit of sense, especially if we decide to make code-gen output a babylon AST.

**Comment by TimothyGu** [comment]
Okay, I've migrated the entire module off babel-traverse and now it relies only on babel-types and babylon (and babylon-walk, which I just wrote in order to provide some features babel-types' `traverseFast` doesn't provide). I also optimized the return unwrapping and globals detecting a bit, so that the AST is reused. Because of these changes, the Babylon version is actually faster than the old Acorn version.

Because acorn-globals still depends on Acorn, I've also created the Babylon-enabled version of it in src/globals.js. I eventually plan to split it out to a separate module, but in-tree version of it should be enough for now.

FWIW, I've also created a Babel plugin for compiling `with` ([babel-plugin-transform-with](https://github.com/pugjs/babel-plugin-transform-with)) with a few more advanced features such as `break` and `continue` handling. That uses the proper Babel AST modification, and is therefore a lot slower too.

**Comment by TimothyGu** [comment]
@ForbesLindesay, could you take a look at this please?

**Comment by ForbesLindesay** [comment]
Sorry I didn't get round to looking at this before you merged it.  It looks like great work.  It would be great to get the globals detection split out again at some point (perhaps under a more generic name) since I know it gets used by some other modules (most notably jsdom).

**Pull request merged**
